### ISSUE TITLE
Invite New User

### ISSUE THREAD

**Issue by TorbiATorbi** [Orangescrum/orangescrum#66]
Hello,

i can't invite new user to a project. 
I get this error message:
Make sure that you have done the below required changes in `app/Config/constants.php` 

But i have setup all constants, and sending an email with 'forgot password' works.

**Comment by Orangescrum** [comment]
Hi TorbiATorbi,
We are sorry for the issue.
Can you please share the constants.php file with us, so that we can get the reason of the issue.

Again one question for you.
Is this the latest version of Orangescrum?
i.e v1.5.6

If not then download the latest version of Orangescrum and install once more.
Because we have fixed the same issue in the latest version.

**Comment by TorbiATorbi** [comment]
I had pulled the last version from git. below my constants.php

```
<?php
########################################################################
##################### Email Sending Options ############################
########################################################################

//Sendgrid smtp
define("SMTP_HOST", "tedo-david");
define("SMTP_PORT", "25");
//https://sendgrid.com/user/signup (free signup to sendgrid)


########################################################################
define("WEB_DOMAIN", "tedo-verlag.de"); //ex. demo.orangescrum.com
define('FROM_EMAIL_NOTIFY', "notify@tedo-verlag.de"); //(REQUIRED)
define('SUPPORT_EMAIL', "support@tedo-verlag.de"); //(REQUIRED) From Email
define('FROM_EMAIL',  'Orangescrum<'.SUPPORT_EMAIL.'>');

define("DEV_EMAIL", 'support@tedo-verlag.de'); // Developer Email ID to report the application error
define('EMAIL_SUBJ', '[Orangescrum]');

// If you have not yet set up the Nohup cronjob, leave it blank
define('EMAIL_REPLY', "<div style='font-family:Arial;font-size:14px;color:#787878;margin-bottom:5px;'>Just REPLY to this Email the same will be added under the Task. <br/><span style='font-size:11px;'><b>NOTE:</b> Do not remove this original message.</span></div>");

define('RELEASE',1); //Increase the release version on every CSS/JS changes to remove the browser cache

##################### Domain and URL Constants ############################
define('SUB_FOLDER', ''); //If your application URL followed by a folder name like: http://your-site.com/folder_name, put your folder name as 'folder_name/'

if(php_sapi_name() === "cli") {
	define('PROTOCOL', "http://");
	define('DOMAIN', "www.my-orangescrum.com/"); // Please set your application domain (REQUIRED)
}else{
	$ht = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS']=='on')?"https://":"http://";
	define('PROTOCOL', $ht);
	if($_SERVER['SERVER_PORT'] != 80)
		define('DOMAIN', $_SERVER['SERVER_NAME'].":".$_SERVER['SERVER_PORT']."/"); 
	else	
		define('DOMAIN', $_SERVER['SERVER_NAME']."/");
}
define('HTTP_SERVER',PROTOCOL.DOMAIN);
define('HTTP_ROOT', HTTP_SERVER.SUB_FOLDER);
define('DOMAIN_COOKIE', $_SERVER['SERVER_NAME']);
define('HTTP_APP', PROTOCOL.DOMAIN.SUB_FOLDER);
define('HTTPS_HOME', PROTOCOL.DOMAIN.SUB_FOLDER);
define('HTTP_HOME', "http://".DOMAIN.SUB_FOLDER);

##################### Google Keys (Login, Drive, Contacts) ############################
define("CLIENT_ID", "XXXXXXXXXXXX.apps.googleusercontent.com");
define("CLIENT_ID_NUM", "XXXXXXXXXXXX");
define("CLIENT_SECRET", "xXxXXxxxx_xXxXXxxxx");
define("API_KEY", "xXxXXxxxxxXXXXXXXXXXXXXxXXxxxx");
define("REDIRECT_URI", HTTP_ROOT."users/googleConnect");

define("USE_GOOGLE", 0); //Set this parameter to 1, to use Google Login, Drive and Contacts

##################### Dropbox Key ############################
define("DROPBOX_KEY", "xXxxXxxxXx");

define("USE_DROPBOX", 0); //Set this parameter to 1, to use Dropbox file sharing

##################### AWS S3 Bucket ############################
define('USE_S3',0); //Set this parameter to 1 to use AWS S3 Bucket
define('BUCKET_NAME', 'Bucket Name');
define('DOWNLOAD_BUCKET_NAME', 'Download Bucket Name');
define('awsAccessKey', 'XXXXXXXXXXXXXX');
define('awsSecretKey', 'XXXX/XXXXXXXXXXXXXX/+XXXXXXXXXXXXXX');
define('DOWNLOAD_S3_TASK_PATH', 'DownloadTask/zipTask/');

define('DIR_CASE_FILES_S3','https://s3.amazonaws.com/'.BUCKET_NAME.'/files/case_files/');
define('DIR_USER_PHOTOS_S3','https://s3.amazonaws.com/'.BUCKET_NAME.'/files/photos/');
define('DIR_USER_PHOTOS_S3_TEMP','https://s3.amazonaws.com/'.BUCKET_NAME.'/files/temp/');
define('DIR_USER_COMPANY_S3','https://s3.amazonaws.com/'.BUCKET_NAME.'/files/company/');
define('DIR_USER_PHOTOS_S3_FOLDER','files/photos/');
define('DIR_USER_COMPANY_S3_FOLDER','files/company/');
define('DIR_CASE_FILES_S3_FOLDER','files/case_files/');
define('DIR_CASE_FILES_S3_FOLDER_TEMP','files/case_files/temp/');

define('MAX_FILE_SIZE', 200); //In Mb
define('CASE_PAGE_LIMIT', 30); // Task Listing Page
define('MILESTONE_PAGE_LIMIT', 5);
define('PROJECT_PAGE_LIMIT', 30);
define('MILE_PAGE_LIMIT', 30);
define('USER_PAGE_LIMIT', 30);
define('ARC_PAGE_LIMIT', 30);
define('MAX_SPACE_USAGE', 1024);
define('MILESTONE_PER_PAGE', 3);
define('ARC_CASE_PAGE_LIMIT',10);
define('ARC_FILE_PAGE_LIMIT',10);
define('TEMP_PROJECT_PAGE_LIMIT', 10);
define('TEMP_TASK_PAGE_LIMIT', 10);

define('TIMELIMIT',3000);

define('ONBORDING',1);
define('ONBORDING_DAILY_UPDATE',1);
define('ONBORDING_DATE','2014-01-01');

define('GMT_DATETIME', gmdate('Y-m-d H:i:s'));
define('GMT_DATE', gmdate('Y-m-d'));
define('GMT_TIME', gmdate('H:i:s'));

define('USE_LOCAL',0);

########## Cookie Settings ############
if(isset($_COOKIE['REMEMBER']) && $_COOKIE['REMEMBER']) {
define('COOKIE_TIME', time()+3600*24*7);
}
else {
define('COOKIE_TIME',time()+3600*2);
}
define('COOKIE_REM',time()+3600*24*30);

define('CSS_PATH', HTTP_ROOT.'css/');
define('JS_PATH', HTTP_ROOT.'js/');


//print "gggggggggggg".WWW_ROOT.$_SERVER['DOCUMENT_ROOT'];exit;
if(WWW_ROOT == 'WWW_ROOT'){
    $w_root = $_SERVER['DOCUMENT_ROOT'].'/'.SUB_FOLDER.'app/webroot/';
    define('DIR_IMAGES', $w_root.'img/');
    define('CSV_PATH', $w_root.'csv/');
    define('DOWNLOAD_TASK_PATH', $w_root.'DownloadTask/');
    define('DIR_FILES', $w_root.'files/');
    define('DIR_CASE_FILES', DIR_FILES.'case_files/');
    define('DIR_USER_PHOTOS', DIR_FILES.'photos/');
}else{
    define('DIR_IMAGES', WWW_ROOT.'img/');
    define('CSV_PATH', WWW_ROOT.'csv/');
    define('DOWNLOAD_TASK_PATH', WWW_ROOT.'DownloadTask/');
    define('DIR_FILES', WWW_ROOT.'files/');
    define('DIR_CASE_FILES', DIR_FILES.'case_files/');
    define('DIR_USER_PHOTOS', DIR_FILES.'photos/');
}
define('DIR_USER_PHOTOS_TEMP', 'files/temp/');
define('DIR_USER_PHOTOS_THUMB', 'files/thumb/');

define('HTTP_IMAGES', HTTP_ROOT.'img/');
define('HTTP_FILES', HTTP_ROOT.'files/');
define('HTTP_CASE_FILES', HTTP_FILES.'case_files/');
define('HTTP_USER_PHOTOS', HTTP_FILES.'photos/');

/**Require socket.io and node.js for instance messaging.**/
//define("NODEJS_HOST",'http://www.your-application.com:3002'); //enable this, if you have Node.js setup in the server
// If you are enabling NODEJS_HOST, make sure you have PHP version >5.3.0
// Also, remove comment on "use ElephantIO\Client as ElephantIOClient" from the following files
// app/Controller/EasycasesController.php, app/Controller/Component/PostcaseComponent.php, app/webroot/EmailReply.php
```

**Comment by khanhicetea** [comment]
You missed the `SMTP_UNAME` and `SMTP_PWORD` parameters in this file.

**Comment by TorbiATorbi** [comment]
the server needs no authentication. thats the reason why i can send me a "password forgotten" e-mail.

**Comment by khanhicetea** [comment]
Orangescrum required those parameters.
Best best case is using SMTP of Gmail or SendGrid.

**Comment by TorbiATorbi** [comment]
Thanks for help. But why i can send me a "password forgotten" e-mail, if Orangescrum needs these parameters?

**Comment by khanhicetea** [comment]
I have just recheck the source code in file `app/Controller/Component/SendgridComponent.php` (Orangescrum use this class to send emails) and see it doesn't require 2 parameters to send mails.

So you can fix your issue by edit file `app/View/Elements/popup.ctp` in line `109`

```php
if(defined('SMTP_PWORD') && SMTP_PWORD != "******") {
```
to
```php
if (true) {
```

This is temporary solution :smiley: , so I recommend using Gmail or Sendgrid SMTP.

**Comment by TorbiATorbi** [comment]
Yes you are right, thats an unnecessary hack....
But thanks for your help!

**Comment by gemchand** [comment]
Hello;

I am inviting new user and send invitation to user. invitation is sent successfully but problem is that invitee did not get any invitation from my side.
and when i am trying to resend invitation it gives me error "Error in sending invitation link!"



can you help for regarding this issue?


Thank You

**Comment by megamatman** [comment]
Hello, I've just encountered the same issue.

The temp solution from my perspective was to:

**1) in app/Config/constants.php:**
Line 19 & 20, set SMTP_UNAME and SMTP_PWORD as follows:-
```
define("SMTP_UNAME", "");
define("SMTP_PWORD", "");
```

**2) in app/Controller/Component/SendgridComponent.php**
Change the $email_array at line 42-49 & line 73-80:

From: 
```
 $email_array = array(
                    'port' => SMTP_PORT,
                    'host' => SMTP_HOST,
                    'username' => SMTP_UNAME,
                    'password' => SMTP_PWORD,
                    'timeout' => '30',
                    'client' => WEB_DOMAIN
                );
```

To:				
```
 $email_array = array(
                    'port' => SMTP_PORT,
                    'host' => SMTP_HOST,
                    //'username' => SMTP_UNAME,
                    //'password' => SMTP_PWORD,
                    'timeout' => '30',
                    'client' => WEB_DOMAIN
                );
```

**Comment by samerkalil** [comment]
how to Invite New User ??

**Comment by fyudelgado** [comment]
Hi Gemchand, 

I'm having the same issue when I try to invite users to a proyect. The message "Error in sending invitation link" still appear!

The log file error in Apache shows these messages:

[Fri Sep 08 19:33:30.790803 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Notice:  Constant EMAIL_DELIVERY already defined in /var/www/orangescrum/app/Config/constants.php on line 12, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.790904 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Stack trace:, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.790929 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   1. {main}() /var/www/orangescrum/app/webroot/index.php:0, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.790943 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   2. include() /var/www/orangescrum/app/webroot/index.php:77, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.790958 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   3. Configure::bootstrap() /var/www/orangescrum/lib/Cake/bootstrap.php:175, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.790971 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   4. include() /var/www/orangescrum/lib/Cake/Core/Configure.php:72, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.790983 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   5. include() /var/www/orangescrum/app/Config/core.php:310, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.790995 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   6. define() /var/www/orangescrum/app/Config/constants.php:12, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791026 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Notice:  Constant SMTP_HOST already defined in /var/www/orangescrum/app/Config/constants.php on line 17, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791048 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Stack trace:, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791062 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   1. {main}() /var/www/orangescrum/app/webroot/index.php:0, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791075 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   2. include() /var/www/orangescrum/app/webroot/index.php:77, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791095 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   3. Configure::bootstrap() /var/www/orangescrum/lib/Cake/bootstrap.php:175, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791108 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   4. include() /var/www/orangescrum/lib/Cake/Core/Configure.php:72, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791152 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   5. include() /var/www/orangescrum/app/Config/core.php:310, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791167 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   6. define() /var/www/orangescrum/app/Config/constants.php:17, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791193 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Notice:  Constant SMTP_PORT already defined in /var/www/orangescrum/app/Config/constants.php on line 18, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791211 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Stack trace:, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791224 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   1. {main}() /var/www/orangescrum/app/webroot/index.php:0, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791236 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   2. include() /var/www/orangescrum/app/webroot/index.php:77, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791256 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   3. Configure::bootstrap() /var/www/orangescrum/lib/Cake/bootstrap.php:175, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791268 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   4. include() /var/www/orangescrum/lib/Cake/Core/Configure.php:72, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791296 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   5. include() /var/www/orangescrum/app/Config/core.php:310, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791309 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   6. define() /var/www/orangescrum/app/Config/constants.php:18, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791334 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Notice:  Constant SMTP_UNAME already defined in /var/www/orangescrum/app/Config/constants.php on line 19, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791351 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Stack trace:, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791364 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   1. {main}() /var/www/orangescrum/app/webroot/index.php:0, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791376 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   2. include() /var/www/orangescrum/app/webroot/index.php:77, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791395 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   3. Configure::bootstrap() /var/www/orangescrum/lib/Cake/bootstrap.php:175, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791407 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   4. include() /var/www/orangescrum/lib/Cake/Core/Configure.php:72, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791425 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   5. include() /var/www/orangescrum/app/Config/core.php:310, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791438 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   6. define() /var/www/orangescrum/app/Config/constants.php:19, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791462 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Notice:  Constant SMTP_PWORD already defined in /var/www/orangescrum/app/Config/constants.php on line 20, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791491 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Stack trace:, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791505 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   1. {main}() /var/www/orangescrum/app/webroot/index.php:0, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791524 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   2. include() /var/www/orangescrum/app/webroot/index.php:77, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791538 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   3. Configure::bootstrap() /var/www/orangescrum/lib/Cake/bootstrap.php:175, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791556 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   4. include() /var/www/orangescrum/lib/Cake/Core/Configure.php:72, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791568 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   5. include() /var/www/orangescrum/app/Config/core.php:310, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791579 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   6. define() /var/www/orangescrum/app/Config/constants.php:20, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791605 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Notice:  Constant WEB_DOMAIN already defined in /var/www/orangescrum/app/Config/constants.php on line 53, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791620 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Stack trace:, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791632 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   1. {main}() /var/www/orangescrum/app/webroot/index.php:0, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791644 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   2. include() /var/www/orangescrum/app/webroot/index.php:77, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791657 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   3. Configure::bootstrap() /var/www/orangescrum/lib/Cake/bootstrap.php:175, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791676 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   4. include() /var/www/orangescrum/lib/Cake/Core/Configure.php:72, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791688 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   5. include() /var/www/orangescrum/app/Config/core.php:310, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791699 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   6. define() /var/www/orangescrum/app/Config/constants.php:53, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791724 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Notice:  Constant FROM_EMAIL_NOTIFY already defined in /var/www/orangescrum/app/Config/constants.php on line 54, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791742 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Stack trace:, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791755 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   1. {main}() /var/www/orangescrum/app/webroot/index.php:0, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791766 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   2. include() /var/www/orangescrum/app/webroot/index.php:77, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791779 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   3. Configure::bootstrap() /var/www/orangescrum/lib/Cake/bootstrap.php:175, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791801 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   4. include() /var/www/orangescrum/lib/Cake/Core/Configure.php:72, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791821 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   5. include() /var/www/orangescrum/app/Config/core.php:310, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791835 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   6. define() /var/www/orangescrum/app/Config/constants.php:54, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791861 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Notice:  Constant SUPPORT_EMAIL already defined in /var/www/orangescrum/app/Config/constants.php on line 55, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791879 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Stack trace:, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791892 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   1. {main}() /var/www/orangescrum/app/webroot/index.php:0, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791903 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   2. include() /var/www/orangescrum/app/webroot/index.php:77, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791923 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   3. Configure::bootstrap() /var/www/orangescrum/lib/Cake/bootstrap.php:175, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791935 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   4. include() /var/www/orangescrum/lib/Cake/Core/Configure.php:72, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791954 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   5. include() /var/www/orangescrum/app/Config/core.php:310, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.791966 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   6. define() /var/www/orangescrum/app/Config/constants.php:55, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792023 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Notice:  Constant FROM_EMAIL already defined in /var/www/orangescrum/app/Config/constants.php on line 56, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792041 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Stack trace:, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792054 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   1. {main}() /var/www/orangescrum/app/webroot/index.php:0, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792065 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   2. include() /var/www/orangescrum/app/webroot/index.php:77, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792078 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   3. Configure::bootstrap() /var/www/orangescrum/lib/Cake/bootstrap.php:175, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792089 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   4. include() /var/www/orangescrum/lib/Cake/Core/Configure.php:72, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792100 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   5. include() /var/www/orangescrum/app/Config/core.php:310, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792118 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   6. define() /var/www/orangescrum/app/Config/constants.php:56, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792155 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Notice:  Constant DEV_EMAIL already defined in /var/www/orangescrum/app/Config/constants.php on line 58, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792174 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Stack trace:, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792187 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   1. {main}() /var/www/orangescrum/app/webroot/index.php:0, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792199 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   2. include() /var/www/orangescrum/app/webroot/index.php:77, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792218 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   3. Configure::bootstrap() /var/www/orangescrum/lib/Cake/bootstrap.php:175, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792231 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   4. include() /var/www/orangescrum/lib/Cake/Core/Configure.php:72, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792248 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   5. include() /var/www/orangescrum/app/Config/core.php:310, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792261 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   6. define() /var/www/orangescrum/app/Config/constants.php:58, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792286 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Notice:  Constant EMAIL_SUBJ already defined in /var/www/orangescrum/app/Config/constants.php on line 59, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792304 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Stack trace:, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792317 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   1. {main}() /var/www/orangescrum/app/webroot/index.php:0, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792329 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   2. include() /var/www/orangescrum/app/webroot/index.php:77, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792348 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   3. Configure::bootstrap() /var/www/orangescrum/lib/Cake/bootstrap.php:175, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792361 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   4. include() /var/www/orangescrum/lib/Cake/Core/Configure.php:72, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792425 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   5. include() /var/www/orangescrum/app/Config/core.php:310, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792447 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   6. define() /var/www/orangescrum/app/Config/constants.php:59, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792469 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Notice:  Constant EMAIL_REPLY already defined in /var/www/orangescrum/app/Config/constants.php on line 62, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792488 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP Stack trace:, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792502 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   1. {main}() /var/www/orangescrum/app/webroot/index.php:0, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792579 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   2. include() /var/www/orangescrum/app/webroot/index.php:77, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792597 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   3. Configure::bootstrap() /var/www/orangescrum/lib/Cake/bootstrap.php:175, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792608 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   4. include() /var/www/orangescrum/lib/Cake/Core/Configure.php:72, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792627 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   5. include() /var/www/orangescrum/app/Config/core.php:310, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited
[Fri Sep 08 19:33:30.792639 2017] [:error] [pid 20179] [client 10.0.0.254:9683] PHP   6. define() /var/www/orangescrum/app/Config/constants.php:62, referer: http://orange.fivetek.mx:8082//users/manage/?role=invited

I don't know why apache sends these errors, when I already setup all these constants on the file.

Did you solve this issue?

Regards,
Francisco Yu

**Comment by khanhicetea** [comment]
```
 PHP Notice: Constant EMAIL_DELIVERY already defined
```
Please notice that every constant must be defined once, so you just remove duplicated one and retry

**Comment by amendez1000** [comment]
Hi everyone,

Greeting from Mexico. I just installed Orangescrum V1.8.0 in Ubuntu 18.04. I checked this:

http://localhost/cron/test_email/?to=mail@hotmail.com

and everything looks fine, I am receiving the e-mail.

However, when I open the form Add New User or Invite New user, the form is open empty. There are not controls, just the Add New User form's title and the option to close.

Do you know what I could be missing?

Thanks!

Regards,
Arturo
