### ISSUE TITLE
How do I debug what's the issue?

### ISSUE THREAD

**Issue by timmolter** [Orangescrum/orangescrum#73]
I installed everything and when I go to the URL I get a HTML page that says:

"There is some Problem
Please check you database connection in `app/Config/database.php` or may be some syntax error"

I triple checked my database connections so I know that's not the issue. How can I see what the actualy cause of the problem is?

**Comment by andola-dev** [comment]
Hi Tim,

Please make below changes to the code , you will be able to see the error message.
---
Navigate to app/config/core.php
Line number 50
change 
Configure::write('debug',0); 
to 
Configure::write('debug',2);

**Comment by timmolter** [comment]
@andola-dev Thanks for the tip. Funny thing is, is that I tried that already, but I couldn't find any errors anywhere. Where exactly will the errors appear?

**Comment by jbolt1236** [comment]
It seems to be an issue with php7 and cakephp version they are using. I looked at my logs and it deals the "String" class which was modified to the CakeText class. I am trying to use the tool, but I do not know CakePhp well enough to fix the issue.

**Comment by rocapal** [comment]
Hi all!

Same problem here. I tried with php5 and php7 in different Debian versions, and it did'nt work. Guys, could you provide some pointers to fix the problem?

**Comment by programster** [comment]
If you want an easy way to deploy orangescrum, you could just [deploy through docker](https://github.com/programster/SCRUMptious).

![selection_644](https://cloud.githubusercontent.com/assets/5709838/13556398/65f77abe-e3d0-11e5-9b89-895c1766673c.png)

I forked the project and created the SCRUMptious version because deployment was such a pain in the butt.

**Comment by rocapal** [comment]
@programster thanks a lot! It was really helpful! 

I have used your SCRUMptious version and it worked perfectly! :-)

**Comment by programster** [comment]
@rocapal thanks. If you have any issues with it, please report on [its issue tracker](https://github.com/programster/SCRUMptious/issues).

**Comment by andyg2** [comment]
I had a similar issue. Initially I went to the setup page which loaded ok. I decided to change an email address in the config and reloaded the page which showed the error. Here's the weird part, I tried to enable `Configure::write('debug',2);` /app/config/core.php but it was now an empty file!
I coped it across from the repo, reloaded and it worked.
Note: I had also inadvertently chmodded the entire installation to 777 which I also fixed when I edited the email.

**Comment by Gordo2** [comment]
Hi. I am a new user of orangescrum and i have an issue that i would like you to sort out. I noticed that when i tried installing Orange scrum using xamp latest versions(7.0 and above), i get a cakephp error telling me that database connection cannot be established and that i should check database.php file for configuration error or syntax errors. After a few days of struggling with this problem i ended up changing xampp version to 5.6 and the orange scrum installed succesfully. Could you guys do something so that Orangescrum can work wth latest xampp versions? This will be very helpful so that programmers don't have to waste too much time in setting up your software. Thankyou.

**Comment by moon759** [comment]
**"There is some Problem  Please check you database connection in app/Config/database.php or may be some syntax error"**

Hi I am facing this issue , please help me to Fix it , i have all the changes  required in database file or in constant file etc.

**Comment by JasonWu93** [comment]
same problem in ubunutu 16.04 @andola-dev  I was chaned here ,but without effct

**Comment by ExtremoCH** [comment]
Same Problem on my system, using Ubuntu 16.04, PHP7, MySQL 5.7. Also get no database connection up, sql_mode is empty. Any idea how to solve?

**Comment by MustafaAdelELnagar** [comment]
Actually, I got bothered from posting issues with no solutions, this is my second time that the project damaged and I couldn't get by, why this bug occurred and how to solve it, I might not using this script again! & the db creditinals are the same and works ! 

 `CakePHP: the rapid development php framework

There is some Problem
Please check you database connection in `app/Config/database.php` or may be some syntax error in your code`

**Comment by MustafaAdelELnagar** [comment]
For developers who didn't know where to find the logs file: 
Go to `app/tmp/logs`

**Comment by MustafaAdelELnagar** [comment]
I have this error, 
```
2017-04-15 20:51:16 Error: Fatal Error (64): Cannot use 'String' as class name as it is reserved in [/mydomain/pm/lib/Cake/Utility/String.php, line 25]
2017-04-15 20:51:16 Error: [InternalErrorException] Internal Server Error
Request URL: /pm/
Stack Trace:
#0 /mydomain/pm/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot use 'Str...', '/mydomain...', 25)
#1 /mydomain/pm/lib/Cake/Core/App.php(929): ErrorHandler::handleError(64, 'Cannot use 'Str...', '/home4/wenitcom...', 25, Array)
#2 /mydomain/pm/lib/Cake/Core/App.php(902): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2017-04-15 20:51:17 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
```

Any advice what I should do ? 
Thanks in advance

**Comment by Gordo2** [comment]
May be abit late to answer this question but i faced the same 

Please check you database connection in app/Config/database.php or may be some syntax error"
If you check and ure sure that the error is not in your databse.php and your syntax is perfect, you might want to consider downgrading your xampp/wampp. I solved it by changing xampp version 7 to version 5 and it worked correctly. You can try your luck with this solution. Some new updates in the latest versions **may** be conflicting with the orange scrum settings.

**Comment by ageof** [comment]
How i fixed this error: 
 [CakeSessionException] Unable to configure the session, setting session.cookie_path failed.
CakeSession.php(187): CakeSession::_configureSession()

**Comment by IacopoOrtis** [comment]
I had the same problem on a DigitalOcean server with MySql 5.7.19, nginx/1.10.3 and PHP7.0.

I get a 500 HTTP error and a page with: 

> There is some Problem
> --
> Please check you database connection in `app/Config/database.php` or may be some syntax error in your code

Having already `Configure::write('debug',2);` I checked the logs in `app/tmp/logs` and I see this:

```
2017-07-31 18:48:09 Error: Fatal Error (64): Cannot use 'String' as class name as it is reserved in [__________________/lib/Cake/Utility/String.php, line 25]
2017-07-31 18:48:09 Error: [InternalErrorException] Internal Server Error
Request URL: /
Stack Trace:
#0 __________________/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot use 'Str...', '__________...', 25)
#1 __________________/lib/Cake/Core/App.php(929): ErrorHandler::handleError(64, 'Cannot use 'Str...', '__________...', 25, Array)
#2 __________________/lib/Cake/Core/App.php(902): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

Clearly a PHP7.0 problem.

# Solution

I searched all "String" class occurrences and replaced it with another name. `"CakeString"` and it worked.

**Comment by Cyril-C** [comment]
While applying IacopoOrtis' solution, I run into some more problems. If dealing with PHP7.0, I do recommend to update the outdated CakePhp library with its latest 2.x version, available at https://github.com/cakephp/cakephp/tree/2.x

Just replace the orangescrum-master/lib/Cake folder with the lib/Cake folder from the above Git repo.

**Comment by TheWhiteF0x** [comment]
@Cyril-C I've applied the solution you've posted. Actually, It have unlocked the application graphics, but I still have the same error on the log-in screen. 
But this time, the logs don't show anything. 

`Request URL: /
Stack Trace:
#0 /var/www/orangescrum/lib/Cake/Model/Model.php(3667): Model->setSource('users')
#1 /var/www/orangescrum/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#2 /var/www/orangescrum/lib/Cake/View/Helper/FormHelper.php(215): Model->schema()
#3 /var/www/orangescrum/lib/Cake/View/Helper/FormHelper.php(480): FormHelper->_introspectModel('User'$
#4 /var/www/orangescrum/app/View/Users/login.ctp(122): FormHelper->create('User', Array)
#5 /var/www/orangescrum/lib/Cake/View/View.php(971): include('/var/www/orange...')
#6 /var/www/orangescrum/lib/Cake/View/View.php(933): View->_evaluate('/var/www/orange...', Array)
#7 /var/www/orangescrum/lib/Cake/View/View.php(473): View->_render('/var/www/orange...')
#8 /var/www/orangescrum/lib/Cake/Controller/Controller.php(963): View->render(NULL, NULL)
#9 /var/www/orangescrum/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#10 /var/www/orangescrum/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersContro$
#11 /var/www/orangescrum/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object($
#12 {main}
`

Is it better on your side ?

**Comment by paulmartimx** [comment]
I've applied the @Cyril-C solution (replacing Cake's version).

It's working for me, no need to disable strict mode or replace String class occurrences.

**Comment by immrakpk** [comment]
My opinion it's a buggy product. Got tired of it after spending a lot of time. There is no to the point guide for this product and frankly there better crm/pmp open source product out there just google it. 

Moral of the store: OrangeScrum SUCKS!!!!!!!

**Comment by linuxman1** [comment]
OrangeScrum is really bugy!!!
